[package]
name = "tracing-glog"
version = "0.1.1"
edition = "2021"
description = "a glog-inspired formatter for tracing-subscriber"
license = "MIT OR Apache-2.0"
readme = "README.md"
homepage = "https://github.com/davidbarsky/tracing-glog"
repository = "https://github.com/davidbarsky/tracing-glog"
documentation = "https://docs.rs/tracing-glog"

[dependencies]
tracing = { version = "0.1", default-features = false }
tracing-subscriber = { version = "0.3.3", features = ["std", "fmt", "registry", "ansi", "time", "local-time"], default-features = false }
time = { version = "0.3.9", features = ["formatting"] }
ansi_term = { version = "0.12" }

[dev-dependencies]
thiserror = "1"
anyhow = "1"
structopt = "0.3"
tracing = { version = "0.1" }
tokio = { version = "1", features = ["full"] }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
